# Generated by Django 4.2.8 on 2023-12-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
