# Generated by Django 4.2.8 on 2023-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_post_content_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stack_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
