# Generated by Django 4.2.8 on 2023-12-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_post_stack_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stack_position',
        ),
    ]
